name: dembuild 
channels:
  - defaults
  - conda-forge
dependencies:
  - conda=4.6.3
  - python=3.7
  - numpy=1.16.3
  - matplotlib=3.0.3
  - gdal=2.3.3
  - pandas=0.24.2
  - geopandas=0.4.1
  - pytz=2019.1
  - scikit-image=0.15.0
  - geos=3.7.1
  - scikit-learn=0.20.3
  - shapely=1.6.4
  - scipy=1.2.1
  - spyder=3.3.4
  - notebook=5.7.8
  - pyproj=1.9.6
  - s3fs=0.2.1
  - gcsfs=0.2.0
  - intake=0.4.1
  - intake-xarray=0.3.0
  - msgpack-python=0.6.1
  - curl=7.64
  - xarray=0.12.0
  - netcdf4
  - h5netcdf
  - h5py
  - bokeh=1.1.0
  - nb_conda_kernels
  - zarr=2.2.0 
  - dask=1.1
  - dask-jobqueue
  - distributed=1.25.2
  - jupyter=1.0.0
  - ipywidgets=7.4.2
  - graphviz=2.38
  - jupyterlab=0.35.4 
  - boto3=1.9.91
  - hvplot=0.4.0
  - geoviews-core=1.6.2
  - ipyleaflet=0.8.1
  - datashader=0.6.9
  - requests=2.21.0
  - rasterio=1.0.18
  - siphon
  - bumpversion=0.5.3
  - wheel=0.32.1
  - flake8=3.5.0
  - tox=3.5.2
  - coverage=4.5.1
  - Sphinx=1.8.1
  - twine=1.12.1
  - pip=18.1
  - pip:
    - sat-search==0.2.0
    - jupyter-server-proxy
    - dask-labextension==0.3.1
    - git+https://github.com/NCAR/intake-thredds




